### ISSUE TITLE
GraphQLError is unhashable

### ISSUE THREAD

**Issue by andrew-humu** [graphql-python/graphql-core-next#34] opened 2019-05-30 03:11 UTC
It seems that the `logging` library in python assumes that exceptions are hashable, in order to be logged.  It'd be great if we could treat GraphQL errors the same way as other builtin exceptions.

See also, a similar issue in the `schematics` project:

https://github.com/schematics/schematics/issues/452

**Comment by Cito** [comment] 2019-05-31 08:39
Thank you for reporting this. The problem is that GraphQLError implements `__eq__` which causes it to loose the default hash capability as Exception. I agree this should be fixed (see #35 for implementation details).

**Closed** 2019-05-31 22:34 UTC
Labels: bug
